### ISSUE TITLE
qUncompress: could not allocate enough memory to uncompress data

### ISSUE THREAD

**Issue by bokuno** [librehat/kdictionary-lingoes#1]
I got this:
qUncompress: could not allocate enough memory to uncompress data
ERROR: Inflated Data is Empty.
I'm on a 32-bit + 2GB ram machine with KDE desktop.
I downloaded a .ld2 dict file from the lingoes website, and try to output it to a .txt file, but it outputted as above.

**Comment by bokuno** [comment]
Thank you for your working! Long time passed before I write this comment, sorry for that :)

**Comment by librehat** [comment]
Welcome. But you might encounter another issue as described in #5
