### ISSUE TITLE
expected constant expression

### ISSUE THREAD

**Issue by mpco** [librehat/kdictionary-lingoes#3]
compile within QT5.4.0 Qt Creator cmake3.1
![capture](https://cloud.githubusercontent.com/assets/3690653/5592258/7fc10862-91ff-11e4-85a4-df785ebf3d08.PNG)

**Comment by librehat** [comment]
What's your compiler?

**Comment by librehat** [comment]
Seems we don't need idxArray. I removed those lines. It'd be okay now.
